# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ON_GOING', 'On Going'), ('ERROR', 'Error'), ('FINISHED', 'Finished')], default='CREATED', max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
